---
server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/senla
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true